# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ugrad/aldenb/group-work/12.01.25/12.01.25.srcs/sources_1/bd/pleasework/ip/pleasework_zynq_ultra_ps_e_0_0/pleasework_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'pleasework_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ugrad/aldenb/group-work/12.01.25/12.01.25.gen/sources_1/bd/pleasework/ip/pleasework_zynq_ultra_ps_e_0_0/pleasework_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pleasework_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ugrad/aldenb/group-work/12.01.25/12.01.25.gen/sources_1/bd/pleasework/ip/pleasework_zynq_ultra_ps_e_0_0/pleasework_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pleasework_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ugrad/aldenb/group-work/12.01.25/12.01.25.srcs/sources_1/bd/pleasework/ip/pleasework_zynq_ultra_ps_e_0_0/pleasework_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'pleasework_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ugrad/aldenb/group-work/12.01.25/12.01.25.gen/sources_1/bd/pleasework/ip/pleasework_zynq_ultra_ps_e_0_0/pleasework_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pleasework_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ugrad/aldenb/group-work/12.01.25/12.01.25.gen/sources_1/bd/pleasework/ip/pleasework_zynq_ultra_ps_e_0_0/pleasework_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pleasework_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
