# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pleasework/pleasework.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework || ORIG_REF_NAME==pleasework} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_zynq_ultra_ps_e_0_0/pleasework_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==pleasework_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_proc_sys_reset_0_0/pleasework_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_proc_sys_reset_0_0 || ORIG_REF_NAME==pleasework_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_smartconnect_0_0/pleasework_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_smartconnect_0_0 || ORIG_REF_NAME==pleasework_smartconnect_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_axi_bram_ctrl_0_0/pleasework_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_axi_bram_ctrl_0_0 || ORIG_REF_NAME==pleasework_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_blk_mem_gen_0_0/pleasework_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_blk_mem_gen_0_0 || ORIG_REF_NAME==pleasework_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_vio_0_0/pleasework_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_vio_0_0 || ORIG_REF_NAME==pleasework_vio_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_util_vector_logic_0_0/pleasework_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_util_vector_logic_0_0 || ORIG_REF_NAME==pleasework_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_xlconstant_0_0/pleasework_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_xlconstant_0_0 || ORIG_REF_NAME==pleasework_xlconstant_0_0} -quiet] -quiet

# IP: bd/pleasework/ip/pleasework_picorv32_axi_0_0/pleasework_picorv32_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pleasework_picorv32_axi_0_0 || ORIG_REF_NAME==pleasework_picorv32_axi_0_0} -quiet] -quiet

# XDC: /home/ugrad/aldenb/group-work/12.01.25/12.01.25.gen/sources_1/bd/pleasework/pleasework_ooc.xdc
